# Generated by Django 5.2.1 on 2025-07-07 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Venue name')),
            ],
            options={
                'verbose_name': 'Venue',
                'verbose_name_plural': 'Venue',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VenueBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Start time')),
                ('end_time', models.DateTimeField(verbose_name='End time')),
                ('booked_by_name', models.CharField(max_length=100, verbose_name='Booking user name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updating time')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venues.venue', verbose_name='Booking venue')),
            ],
            options={
                'verbose_name': 'Venue booking record',
                'verbose_name_plural': 'Venue booking record',
                'ordering': ['-created_at', 'venue'],
            },
        ),
    ]
