# Generated by Django 5.1.6 on 2025-05-13 13:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_studentprofile_department_employeeprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
